POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit 2",
  "details": "Outro evento",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/c740d7b6-36be-468f-b57e-098f6b51b182/attendees
Content-Type: application/json

{
  "name": "Alexia",
  "email": "alexia@example.com"
}